### PR TITLE
Further details for nodes added (skip count and reported date on overview page)

### PR DESCRIPTION
**Pull request by fgimian**
Hey there again,

I've added a skip count for each node on the overview page along with a reported column which is very helpful on the overview page.

Cheers
Fotis

### CODE REVIEW

**Comment by daenney** [comment]
Could you squash this down a bit? dfd9007, 51efb12 and 383d6b6 appear to be working on getting the same feature working, in which case I'd rather see that as 1 commit in the history instead of 4.

**Comment by fgimian** [comment]
Done mate, please let me know if that's OK now :smile:

**Comment by daenney** [comment]
You're fast :smile:

**Comment by fgimian** [comment]
Hehe, thanks so much, so are you! :smile:

**Pull request merged**
