### PR TITLE
Allow configuration of default environment

### PR DESCRIPTION
**Pull request by raphink**
Because not everyone might want to use 'production'.

### CODE REVIEW

**Comment by mcanevet** [comment]
+1

**Comment by raphink** [comment]
ping @corey-hammerton

**Comment by daenney** [comment]
@raphink Give him some time. Uncool to just go ping around a couple of hours after opening a PR.

**Comment by nibalizer** [comment]
:+1:

**Comment by raphink** [comment]
@daenney lately I don't get notifications when someone opens a PR against my projects, so I'm just making sure people get one, I don't mean to be pushy :-)

**Comment by corey-hammerton** [comment]
@raphink Can you make direct references to ``app.config['DEFAULT_ENVIRONMENT']`` instead of ``default_env`` in all the ``app.route`` changes?

**Comment by raphink** [comment]
OK I can do that.

**Comment by raphink** [comment]
@corey-hammerton there you go.

**Comment by corey-hammerton** [comment]
:+1:

**Comment by raphink** [comment]
@corey-hammerton Is something still missing for this PR?

**Comment by corey-hammerton** [comment]
Nothing appears to be missing, I just haven't had a chance to work on the project. Should be able to get to it later today.

**Comment by raphink** [comment]
OK, just wanted to make sure :-)

**Pull request merged**
