### PR TITLE
Adds custom facts to enumerate in nodes list

### PR DESCRIPTION
**Pull request by vjanelle**
Enumerates a specific fact to show during the node list, which is
configurable as NODES_FACTS in the configuration.

I've added a default entry which is empty, and some detection around if
a fact doesn't exist on a value (which should just print none).

### CODE REVIEW

**Comment by daenney** [comment]
Right. This seems sensible to me. Do you have a screenshot or two, to see how this behaves? I don't have a PuppetDB at hand with sane data to try out your PR right now.

**Comment by vjanelle** [comment]
https://www.evernote.com/shard/s21/sh/ba3bf558-9bfb-442f-bb4f-34708f3eccf2/07afe49672f85385cc9349c8cea523d1/deep/0/Puppetboard.png

**Comment by vjanelle** [comment]
The nodes display panel on the index page has some odd formatting, due to the weights put on the hostname - the two fields I specified get shoved waaaay to the right.

**Comment by daenney** [comment]
Mmm, interesting. I can see this being useful. I'm back at home after the weekend with a functioning PuppetDB, I'll see what I can do about the formatting.

**Comment by vjanelle** [comment]
\o/

**Comment by Poil** [comment]
When I merge this patch I've got an error per node: 
```
 [error] INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): puppetdb.xxxxxxxxxx.xxxxx
```

**Comment by daenney** [comment]
That's some weird error logging. That message is logged as `INFO` by the python `logging` library, how does it end up with an `[error]` tag on your side?

**Comment by vjanelle** [comment]
I've rebased this so it should be mergeable again.

**Pull request closed without merging**
