### PR TITLE
Event Browser

### PR DESCRIPTION
**Pull request by juliushaertl**
These commits bring a simple event browser into puppetboard, similar to the event inspector in Puppet Enterprise. 

You can browse events of the latest reports grouped by nodes, containing-class or resource and get details on every event.

eventbrowser

### CODE REVIEW

**Comment by fgimian** [comment]
This looks great, I'll be reviewing it soon and attempting to redesign it so we can merge.  Thanks for your contribution :smile:

**Comment by nibalizer** [comment]
@fgimian did you get anywhere on a redesign?

**Comment by fgimian** [comment]
@nibalizer not just yet I'm afraid, I intend to put in a chunk of time in the coming week or two :smile:

**Comment by corey-hammerton** [comment]
@fgimian Have  you been able to work on the redesign?

**Comment by fgimian** [comment]
@corey-hammerton Sorry, not really. My workplace has moved to using Red Hat Satellite (which is built on top of Foreman) so I am no longer actively contributing to Puppetboard at the moment.  Perhaps someone else can take a look? :smile:

**Comment by corey-hammerton** [comment]
With that said I will close this PR.

**Pull request closed without merging**
