### PR TITLE
Possibility to list only reports w/ changes

### PR DESCRIPTION
**Pull request by rafaelhenrique**
Hi! This PR is my first PR are not angry with me :/... 
This PR was opened to solve the issue #127 ... review please!

Thanks! ;)

### CODE REVIEW

**Comment by nibalizer** [comment]
@rafaelhenrique can you [squash](http://www.git-scm.com/book/en/Git-Tools-Rewriting-History#Squashing-Commits) this into a single commit?

**Comment by rafaelhenrique** [comment]
Sure! And i need create a new PR after this??

**Comment by rafaelhenrique** [comment]
Could someone tell me how to proceed after the squash?

**Comment by nibalizer** [comment]
Squash the commits. Then git push -f origin master

**Comment by rafaelhenrique** [comment]
Thanks @nibalizer I'll do it now

**Comment by rafaelhenrique** [comment]
Done... review please ;)

**Comment by nibalizer** [comment]
:+1:

**Comment by rtib** [comment]
I've tested it. It works as expected. :+1:

**Comment by rafaelhenrique** [comment]
And anyone can merge? If not explain to me please ... :/

**Comment by nibalizer** [comment]
I don't fell confident merging this since this is really @daenney's project. We'll see if he has time to review it soon and if not we'll decide what to do then.

**Comment by rafaelhenrique** [comment]
Ok. Thanks ;)

**Comment by nibalizer** [comment]
@rafaelhenrique if you can rebase this against master we can move forward with merging it.

**Comment by rafaelhenrique** [comment]
Done @nibalizer :+1:

**Comment by nibalizer** [comment]
?

**Comment by nibalizer** [comment]
Is there still interest in this patch? Sorry we've been unresponsive. There is a big load and we're always looking for more contributors.

**Comment by janorn** [comment]
I vote for this patch! It is more interesting to be able to se what has happened than that nothing happened. Perhaps there should be a label with the last report just to validate that it has run.

**Comment by nibalizer** [comment]
@janorn or @rtib can you try the re-upload of this on #160 then ping me aggressively until I merge it? For the record the best place to yell is on irc in #puppet-community or on twitter.

**Comment by rafaelhenrique** [comment]
Too late

**Pull request closed without merging**
