### PR TITLE
puppetboard: Adding Catalog Viewer

### PR DESCRIPTION
**Pull request by corey-hammerton**
This makes use of the available catalog endpoints in pypuppetdb and PuppetDB
and displays to administrators the last compiled catalog for a node,
if the variable ENABLE_CATALOG is True (defaults to False)

This is a re-work of https://github.com/puppet-community/puppetboard/pull/93 and https://github.com/puppet-community/puppetboard/pull/115

### CODE REVIEW

**Comment by nibalizer** [comment]
I've tested this locally and lgtm. @daenney I'll give you a bit of time to poke it then I'll merge.

**Comment by daenney** [comment]
I don't have something useful to test this against so can't do much poking. Use your best judgement :smile:.

**Comment by janorn** [comment]
Is this catalog only supposed to be reachable via the nodes tab?
I doesn't seem to be available from the individual node page.

**Comment by corey-hammerton** [comment]
@janorn This is just an initial implementation of this functionality. There is always room for improvement.

**Comment by nibalizer** [comment]
I agree, I think maybe having a 'Catalogs' at the top and then a per node list might make more sense.

**Comment by corey-hammerton** [comment]
I should be able to put more effort into the catalogs when I'm working on the upgrades required for PuppetDB 3.x. That is going to be my next task on this project.

**Comment by nibalizer** [comment]
Awesome. Also if we could get pagination in pypuppetdb I would be /so/ happy. Also feel free to join #puppetboard and or #puppet-community on freenode to chat with us.

**Comment by corey-hammerton** [comment]
I've started my work on the PuppetDB 3.x work, it's available here: https://github.com/corey-hammerton/puppetboard/tree/puppetdb-3.0

**Comment by corey-hammerton** [comment]
Also: https://github.com/corey-hammerton/puppetboard/commit/30e1cfef4a56968a37daad27c0d13a07b53bf588

**Pull request merged**
