### PR TITLE
Pr 129

### PR DESCRIPTION
**Pull request by nibalizer**
This is a re-up of #129

### CODE REVIEW

**Comment by corey-hammerton** [comment]
Giving that we are developing and testing on PuppetDB 3.x systems would it be better if we did any one of the following?

1. Query the reports endpoint where status is not 'unchanged' and noop is false
2. Display report status information like the node status is shown on the Overview and Nodes pages

Also since we're planning on removing the ``limit_reports`` function it might be better to close and re-think this PR

**Comment by daenney** [comment]
Yeah. With pagination in place `limit_reports` needs to go.

**Comment by corey-hammerton** [comment]
``limit_reports`` is removed in https://github.com/puppet-community/puppetboard/pull/176. Along with showing the report status in the node reports table and the reports tab (which is now fully functional)

**Comment by nibalizer** [comment]
Closing

**Pull request closed without merging**
