### PR TITLE
Feature: adding examples directory

### PR DESCRIPTION
**Pull request by visibilityspots**
I hereby added an examples directory where projects which show off the puppetboard in various manners can be added.

### CODE REVIEW

**Comment by stack72** [comment]
@visibilityspots If I am reading this PR right, this is adding a vagrant playground to see Puppetboard in action - correct?

**Comment by visibilityspots** [comment]
@stack72 yes indeed, I added an examples directory which consists a first submodule pointing to a vagrant playground which is provided by puppet.

**Comment by nibalizer** [comment]
@visibilityspots can you add some README stuff to explain how to use this?

**Comment by nibalizer** [comment]
I would rather just a link in the readme than a submodule.

**Comment by daenney** [comment]
I don't think the whole submodule thing is a great idea either. If it was a dependency that we needed to vendor, sure, but for some examples, no. Little section in the README plus a link to the repository would be enough.

**Pull request closed without merging**
