### PR TITLE
Adding Catalog viewer

### PR DESCRIPTION
**Pull request by corey-hammerton**
Squashed commit of https://github.com/puppet-community/puppetboard/pull/93

### CODE REVIEW

**Comment by daenney** [comment]
Thank you! I'll look at it this week.

**Comment by corey-hammerton** [comment]
Does anybody think this will be a good idea to implement?

**Comment by corey-hammerton** [comment]
@nibalizer, are there any plans/objections with getting this merged?

**Comment by nibalizer** [comment]
It says it has merge conflicts. I just tested it out in our systems and it works fine. Fix the conflicts and boom it is in.

**Comment by nibalizer** [comment]
@corey-hammerton ^^

**Comment by corey-hammerton** [comment]
Thank you for the response. 

I will have to create another pull request to fix the conflicts since I must have deleted my original repository.

**Comment by nibalizer** [comment]
Nah you're good.
```bash
    id=115
    git fetch origin pull/${id}/head:pr_${id};
    git checkout pr_${id}
```

Will let you see the current state of this code.

**Comment by nibalizer** [comment]
For future work, not required for this patch, being able to diff the catalog of two nodes would be super legit.

**Comment by nibalizer** [comment]
Also I think I'd prefer if the catalog viewer was disabled by default, since it can leak security information.

**Comment by corey-hammerton** [comment]
Unfortunately I cannot seem to push any more commits to this Pull Request, Therefore I am force to close this PR in favour of https://github.com/puppet-community/puppetboard/pull/156

**Pull request closed without merging**
