### PR TITLE
Add scroll to top button

### PR DESCRIPTION
**Pull request by juliengk**

### CODE REVIEW

**Comment by daenney** [comment]
Could you quickly add a screen cap to this PR? Not as a commit, just drag it into the comment field so we can see what this ends up looking like.

**Comment by juliengk** [comment]
top-button

**Comment by juliengk** [comment]
Let me know if you want to change the size, color...

**Comment by daenney** [comment]
I really have no problems with this, if anything it'll come in useful. We can always tweak the UI later, no need to have the PR hanging any longer.

**Pull request merged**
